# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reach_Rcpp <- function(Y, X, Z, penalty, U0, V0, W0, r, lb, lw, rho, a, epsilon, maxiter, inner_epsilon, inner_maxiter) {
    .Call(`_reach_reach_Rcpp`, Y, X, Z, penalty, U0, V0, W0, r, lb, lw, rho, a, epsilon, maxiter, inner_epsilon, inner_maxiter)
}

